export const Receipt = {
  REQUEST_GET_LIST_RECEIPT: 'REQUEST_GET_LIST_RECEIPT',
  REQUEST_READ_RECEIPT    : 'REQUEST_READ_RECEIPT',
  FAIL_REQUEST_RECEIPT    : 'FAIL_REQUEST_RECEIPT',
  NO_HAVE_NEW_RECEIPT     : 'NO_HAVE_NEW_RECEIPT',
  READ_RECEIPT            : 'READ_RECEITPT',
  GET_LIST_RECEIPT        : 'GET_LIST_RECEIPT'
}

export const Course = {
  REQUEST_BOOK_COURSE: 'REQUEST_BOOK_COURSE',
  FAIL_REQUEST_COURSE: 'FAIL_REQUEST_COURSE',
  BOOK_COURSE        : 'BOOK_COURSE'
}
